package main;

public class Main {
    public static void main(String[] args) {

        //Generate the cars and drivers. Values are generated by Copilot.
        RallyCar car1 = new GravelCar("Subaru", "Impreza", 300, 10);
        RallyCar car2 = new GravelCar("Mitsubishi", "Lancer", 280, 8);
        RallyCar car3 = new GravelCar("Ford", "Focus", 250, 6);
        RallyCar car4 = new GravelCar("Toyota", "Celica", 270, 7);
        RallyCar car5 = new GravelCar("Peugeot", "206", 260, 5);

        Driver driver1 = new Driver("John", "USA", car1);
        Driver driver2 = new Driver("Michael", "UK", car2);
        Driver driver3 = new Driver("David", "Australia", car3);
        Driver driver4 = new Driver("Mark", "Canada", car4);
        Driver driver5 = new Driver("Paul", "Germany", car5);

        ChampionshipManager manager = ChampionshipManager.getInstance();

        //Register the drivers
        manager.registerDriver(driver1);
        manager.registerDriver(driver2);
        manager.registerDriver(driver3);
        manager.registerDriver(driver4);
        manager.registerDriver(driver5);

        // Races that are held
        RallyRaceResult finlandRaceResult = new RallyRaceResult("Rally Finland", "Jyväskylä");
        finlandRaceResult.recordResult(driver1,1,25);
        finlandRaceResult.recordResult(driver4,2, 18);
        finlandRaceResult.recordResult(driver5,3, 15);
        finlandRaceResult.recordResult(driver3,4, 12);
        finlandRaceResult.recordResult(driver2,5, 10);

        manager.addRaceResults(finlandRaceResult);

        // Change the cars to Asphalt cars
        car1 = new AsphaltCar("Subaru", "Impreza", 320, 12);
        car2 = new AsphaltCar("Mitsubishi", "Lancer", 300, 10);
        car3 = new AsphaltCar("Ford", "Focus", 280, 8);
        car4 = new AsphaltCar("Toyota", "Celica", 290, 9);
        car5 = new AsphaltCar("Peugeot", "206", 270, 7);

        driver1.setCar(car1);
        driver2.setCar(car2);
        driver3.setCar(car3);
        driver4.setCar(car4);
        driver5.setCar(car5);

        RallyRaceResult monacoRaceResult = new RallyRaceResult("Monte Carlo Rally", "Monaco");
        monacoRaceResult.recordResult(driver4,1, 25);
        monacoRaceResult.recordResult(driver1,2, 18);
        monacoRaceResult.recordResult(driver5,3, 15);
        monacoRaceResult.recordResult(driver2,4, 12);
        monacoRaceResult.recordResult(driver3,5, 10);

        manager.addRaceResults(monacoRaceResult);

        // Print the results
        System.out.println("===== CHAMPIONSHIP STANDINGS =====");
        int position = 1;
        for (Driver driver : manager.getDriverStandings()) {
            System.out.println(position + ": " + driver.getName() + "(" + driver.getCountry() + ") : " + driver.getPoints() + " points.");
            position++;
        }

        System.out.println("\n===== CHAMPIONSHIP LEADER =====");
        Driver leader = ChampionshipManager.getLeadingDriver();
        System.out.println(leader.getName() + " with " + leader.getPoints() + " points");

        System.out.println("\n===== CHAMPIONSHIP STATISTICS =====");
        System.out.println("Total Drivers: " + ChampionshipManager.getTotalDrivers());
        System.out.println("Total Races: " + ChampionshipManager.getTotalRaces());
        System.out.printf("Average Points Per Driver: %.2f\n", 
                ChampionshipStatistics.calculateAveragePointsPerDriver(manager.getDriverStandings()));
        System.out.println("Most Successful Country: " + 
                ChampionshipStatistics.findMostSuccessfulCountry(manager.getDriverStandings()));
        System.out.println("Total Championship Points: " + ChampionshipManager.getTotalChampionshipPoints());

        System.out.println("\n===== RACE RESULTS =====");
        System.out.println(finlandRaceResult);
        for (Driver driver : finlandRaceResult.getResults()) {
            System.out.println(driver.getName() + ": " + finlandRaceResult.getDriverPoints(driver) + " points");
        }
        System.out.println(monacoRaceResult);
        for (Driver driver : monacoRaceResult.getResults()) {
            System.out.println(driver.getName() + ": " + monacoRaceResult.getDriverPoints(driver) + " points");
        }

        System.out.println("\n===== CAR PERFORMANCE RATINGS =====");
        System.out.println(car1);
        System.out.println(car2);

    }
}
